### ISSUE TITLE
Suporte a apenas um perfil nas redes sociais.

### ISSUE THREAD

**Issue by rafasgj** [tchelinux/people#3]
Em algumas redes sociais são permitidos o uso de mais de um perfil. Caso de uso bastante comum para o Instagram, por exemplo.

A sugestão é aceitar um conjunto de valores para redes sociais, e adicionar um link para cada perfil.

**Comment by leonardovaz** [comment]
Podemos fazer isso estendendo o JSON, só que agora não é prioridade.
