### ISSUE TITLE
Por que usar diretórios?

### ISSUE THREAD

**Issue by rafasgj** [tchelinux/people#4]
Como cada usuário terá apenas um arquivo JSON descrevendo seus dados, poderíamos ter um único diretório `people` e os nomes de arquivos possuirem o formato `<username>.json`

**Comment by leonardovaz** [comment]
Apenas pra simplificar a questão do namespace e uma vez que temos toda a geração e manuseio dos links sendo de forma estática não precisamos lidar com arquivos e extensões.
